name: Backend build and tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build in python3
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: |
        python -m pip install build
        python -m build